// --- KUMPULAN LOGIKA MINI GAMES MOCCA APP ---

// 1. LOGIKA GAME JARI PETIR
let tapScore = 0; let tapTime = 10; let tapTimerInterval = null; let isTapPlaying = false;
window.bukaTapGame = () => { document.getElementById('tap-game-modal').classList.remove('hidden'); document.getElementById('tap-highscore').innerText = localStorage.getItem('tapHighScore') || 0; tapScore = 0; tapTime = 10; isTapPlaying = false; document.getElementById('tap-score').innerText = 0; document.getElementById('tap-timer').innerText = "10.00"; document.getElementById('tap-status').innerText = "Tekan MULAI untuk main"; document.getElementById('btn-tap-action').disabled = true; }
window.initTapGame = () => { tapScore = 0; tapTime = 10; isTapPlaying = true; document.getElementById('tap-status').innerText = "TAP SECEPAT MUNGKIN!"; document.getElementById('btn-tap-action').disabled = false; tapTimerInterval = setInterval(() => { tapTime -= 0.01; document.getElementById('tap-timer').innerText = tapTime.toFixed(2); if(tapTime <= 0) { clearInterval(tapTimerInterval); isTapPlaying = false; document.getElementById('btn-tap-action').disabled = true; document.getElementById('tap-timer').innerText = "0.00"; const highScore = localStorage.getItem('tapHighScore') || 0; if(tapScore > highScore) { localStorage.setItem('tapHighScore', tapScore); document.getElementById('tap-highscore').innerText = tapScore; alert(`REKOR BARU! 🔥\nSkor Kamu: ${tapScore}`); } else { alert(`Waktu Habis!\nSkor Kamu: ${tapScore}`); } } }, 10); }
window.tapClick = () => { if(isTapPlaying) { tapScore++; document.getElementById('tap-score').innerText = tapScore; if (navigator.vibrate) navigator.vibrate(20); } }

// 2. LOGIKA GAME FLAPPY MOCCA
let canvas, ctx; let frames = 0; let score = 0; let gameLoopId; let bird = { x: 50, y: 150, w: 40, h: 40, radius: 20, v: 0, gravity: 0.25, jump: 4.6, rotation: 0 }; let pipes = []; let state = { current: 0, getReady: 0, game: 1, over: 2 }; const gap = 120; let birdImg = new Image();
window.bukaFlappy = () => { document.getElementById('flappy-game-modal').classList.remove('hidden'); canvas = document.getElementById('flappyCanvas'); ctx = canvas.getContext('2d'); canvas.width = canvas.clientWidth; canvas.height = canvas.clientHeight; birdImg.src = document.getElementById('user-photo').src || 'icon.png'; bird.y = 150; bird.v = 0; pipes = []; score = 0; frames = 0; state.current = state.getReady; document.getElementById('flappy-score-display').innerText = 0; document.getElementById('flappy-start-msg').classList.remove('hidden'); gameLoopId = requestAnimationFrame(loopFlappy); canvas.addEventListener("click", flapAction); window.addEventListener("keydown", (e) => { if(e.code === "Space") flapAction(); }); }
function flapAction() { if (state.current === state.getReady) { state.current = state.game; document.getElementById('flappy-start-msg').classList.add('hidden'); } else if (state.current === state.game) { bird.v = -bird.jump; } else if (state.current === state.over) { bird.y = 150; bird.v = 0; pipes = []; score = 0; frames = 0; state.current = state.getReady; document.getElementById('flappy-score-display').innerText = 0; document.getElementById('flappy-start-msg').classList.remove('hidden'); } }
function loopFlappy() { updateFlappy(); drawFlappy(); gameLoopId = requestAnimationFrame(loopFlappy); }
function updateFlappy() { if (state.current === state.getReady) return; if (state.current === state.game) { bird.v += bird.gravity; bird.y += bird.v; if(bird.y + bird.h/2 >= canvas.height || bird.y - bird.h/2 <= 0) { state.current = state.over; } if (frames % 120 === 0) { pipes.push({ x: canvas.width, y: Math.random() * (canvas.height - 300) + 150 }); } for(let i = 0; i < pipes.length; i++) { let p = pipes[i]; p.x -= 2; let birdLeft = bird.x - bird.radius; let birdRight = bird.x + bird.radius; let birdTop = bird.y - bird.radius; let birdBottom = bird.y + bird.radius; let pipeTopBottom = p.y - gap/2; let pipeBotTop = p.y + gap/2; if(birdRight > p.x && birdLeft < p.x + 50) { if(birdTop < pipeTopBottom || birdBottom > pipeBotTop) { state.current = state.over; } } if(p.x + 50 < 0) { pipes.shift(); score++; document.getElementById('flappy-score-display').innerText = score; } } frames++; } }
function drawFlappy() { ctx.fillStyle = "#70c5ce"; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = "#73bf2e"; ctx.strokeStyle = "#538d22"; ctx.lineWidth = 2; for(let i = 0; i < pipes.length; i++) { let p = pipes[i]; ctx.fillRect(p.x, 0, 50, p.y - gap/2); ctx.strokeRect(p.x, 0, 50, p.y - gap/2); ctx.fillRect(p.x, p.y + gap/2, 50, canvas.height - (p.y + gap/2)); ctx.strokeRect(p.x, p.y + gap/2, 50, canvas.height - (p.y + gap/2)); } ctx.save(); ctx.translate(bird.x, bird.y); ctx.rotate(bird.v * 0.1); ctx.beginPath(); ctx.arc(0, 0, bird.radius, 0, Math.PI*2, true); ctx.closePath(); ctx.clip(); ctx.drawImage(birdImg, -bird.radius, -bird.radius, bird.w, bird.h); ctx.restore(); ctx.beginPath(); ctx.arc(bird.x, bird.y, bird.radius, 0, Math.PI*2, true); ctx.lineWidth = 2; ctx.strokeStyle = "white"; ctx.stroke(); if(state.current === state.over) { ctx.fillStyle = "rgba(0,0,0,0.5)"; ctx.fillRect(0,0,canvas.width, canvas.height); ctx.fillStyle = "white"; ctx.font = "30px 'Press Start 2P'"; ctx.fillText("GAME OVER", canvas.width/2 - 120, canvas.height/2); ctx.font = "15px Arial"; ctx.fillText("Ketuk untuk main lagi", canvas.width/2 - 60, canvas.height/2 + 40); } }

// 3. LOGIKA GAME PUKUL BUG
let whackScore = 0; let whackTime = 15; let lastHole; let whackTimerInterval; let whackUpInterval; window.isWhackPlaying = false;
window.bukaWhackGame = () => { document.getElementById('whack-game-modal').classList.remove('hidden'); document.getElementById('whack-score').innerText = 0; document.getElementById('whack-time').innerText = 15; }
function randomTime(min, max) { return Math.round(Math.random() * (max - min) + min); }
function randomHole(holes) { const idx = Math.floor(Math.random() * holes.length); const hole = holes[idx]; if (hole === lastHole) return randomHole(holes); lastHole = hole; return hole; }
function peep() { const holes = document.querySelectorAll('.hole'); const time = randomTime(400, 1000); const hole = randomHole(holes); const bug = hole.querySelector('.bug'); bug.classList.add('up'); setTimeout(() => { bug.classList.remove('up'); if (window.isWhackPlaying) peep(); }, time); }
window.startWhackGame = () => { whackScore = 0; whackTime = 15; window.isWhackPlaying = true; document.getElementById('whack-score').innerText = 0; document.getElementById('whack-time').innerText = 15; document.getElementById('btn-whack-start').disabled = true; document.getElementById('btn-whack-start').innerText = "BASMI SEKARANG!"; peep(); whackTimerInterval = setInterval(() => { whackTime--; document.getElementById('whack-time').innerText = whackTime; if(whackTime <= 0) { clearInterval(whackTimerInterval); window.isWhackPlaying = false; document.getElementById('btn-whack-start').disabled = false; document.getElementById('btn-whack-start').innerText = "MULAI BASMI LAGI"; alert(`WAKTU HABIS! Skor Basmi: ${whackScore}`); } }, 1000); }
setTimeout(() => { document.querySelectorAll('.bug').forEach(bug => { bug.addEventListener('click', function() { if(!window.isWhackPlaying) return; whackScore++; this.classList.remove('up'); document.getElementById('whack-score').innerText = whackScore; if (navigator.vibrate) navigator.vibrate(50); }); }); }, 1000);

// 4. LOGIKA GAME ULAR KLASIK
let snakeCanvas, sCtx, snake, food, snakeDir, snakeGameLoop; const box = 20; 
window.bukaSnakeGame = () => { document.getElementById('snake-game-modal').classList.remove('hidden'); snakeCanvas = document.getElementById('snakeCanvas'); sCtx = snakeCanvas.getContext("2d"); }
window.initSnakeGame = () => { document.getElementById('btn-snake-start').classList.add('hidden'); snake = []; snake[0] = { x: 9 * box, y: 10 * box }; food = { x: Math.floor(Math.random()*15) * box, y: Math.floor(Math.random()*15) * box }; snakeDir = ""; let score = 0; document.getElementById('snake-score').innerText = score; if(snakeGameLoop) clearInterval(snakeGameLoop); snakeGameLoop = setInterval(drawSnake, 150); }
window.changeSnakeDir = (dir) => { if(dir === "Left" && snakeDir !== "Right") snakeDir = "Left"; if(dir === "Up" && snakeDir !== "Down") snakeDir = "Up"; if(dir === "Right" && snakeDir !== "Left") snakeDir = "Right"; if(dir === "Down" && snakeDir !== "Up") snakeDir = "Down"; }
function drawSnake() { sCtx.fillStyle = "#1e293b"; sCtx.fillRect(0, 0, 300, 300); for(let i = 0; i < snake.length; i++) { sCtx.fillStyle = (i === 0) ? "#4ade80" : "#22c55e"; sCtx.fillRect(snake[i].x, snake[i].y, box, box); sCtx.strokeStyle = "#1e293b"; sCtx.strokeRect(snake[i].x, snake[i].y, box, box); } sCtx.fillStyle = "red"; sCtx.fillRect(food.x, food.y, box, box); let snakeX = snake[0].x; let snakeY = snake[0].y; if(snakeDir == "Left") snakeX -= box; if(snakeDir == "Up") snakeY -= box; if(snakeDir == "Right") snakeX += box; if(snakeDir == "Down") snakeY += box; if(snakeX == food.x && snakeY == food.y) { let score = parseInt(document.getElementById('snake-score').innerText); score++; document.getElementById('snake-score').innerText = score; food = { x: Math.floor(Math.random()*15) * box, y: Math.floor(Math.random()*15) * box }; } else { snake.pop(); } let newHead = { x : snakeX, y : snakeY }; if(snakeX < 0 || snakeX > 280 || snakeY < 0 || snakeY > 280 || collision(newHead, snake)) { clearInterval(snakeGameLoop); document.getElementById('btn-snake-start').classList.remove('hidden'); document.getElementById('btn-snake-start').innerText = "ULANGI"; alert("GAME OVER! Skor: " + document.getElementById('snake-score').innerText); } snake.unshift(newHead); }
function collision(head, array) { for(let i = 0; i < array.length; i++) { if(head.x == array[i].x && head.y == array[i].y) return true; } return false; }

// 5. LOGIKA GAME TIC-TAC-TOE
let tttBoard = ["", "", "", "", "", "", "", "", ""];
let tttPlayer = "X";
let tttActive = true;
const tttWinConditions = [ [0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6] ];
window.mainTTT = function(index) { if (tttBoard[index] !== "" || !tttActive) return; tttBoard[index] = tttPlayer; let cell = document.getElementById(`ttt-${index}`); cell.innerText = tttPlayer; if (tttPlayer === "X") { cell.classList.add("text-blue-500", "dark:text-blue-400"); } else { cell.classList.add("text-rose-500", "dark:text-rose-400"); } cekMenangTTT(); };
function cekMenangTTT() { let won = false; for (let i = 0; i < tttWinConditions.length; i++) { const [a, b, c] = tttWinConditions[i]; if (tttBoard[a] !== "" && tttBoard[a] === tttBoard[b] && tttBoard[a] === tttBoard[c]) { won = true; break; } } const statusText = document.getElementById('ttt-status'); if (won) { statusText.innerText = `Yeay! ${tttPlayer} Menang! 🎉`; statusText.className = "bg-green-100 text-green-800 dark:bg-green-900/40 dark:text-green-300 px-5 py-2 rounded-full text-sm font-bold shadow-sm transition-all"; tttActive = false; return; } if (!tttBoard.includes("")) { statusText.innerText = "Yahh Seri! 🤝"; statusText.className = "bg-gray-200 text-gray-800 dark:bg-gray-700 dark:text-gray-300 px-5 py-2 rounded-full text-sm font-bold shadow-sm transition-all"; tttActive = false; return; } tttPlayer = tttPlayer === "X" ? "O" : "X"; statusText.innerText = `Giliran: ${tttPlayer}`; }
window.resetTTT = function() { tttBoard = ["", "", "", "", "", "", "", "", ""]; tttPlayer = "X"; tttActive = true; const statusText = document.getElementById('ttt-status'); statusText.innerText = "Giliran: X"; statusText.className = "bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300 px-5 py-2 rounded-full text-sm font-bold shadow-sm transition-all"; for (let i = 0; i < 9; i++) { let cell = document.getElementById(`ttt-${i}`); cell.innerText = ""; cell.classList.remove("text-blue-500", "dark:text-blue-400", "text-rose-500", "dark:text-rose-400"); } };

// 6. LOGIKA GAME MEMORY CARD
const memoryIcons = [ '<i class="fa-solid fa-mug-hot"></i>', '<i class="fa-solid fa-laptop"></i>', '<i class="fa-solid fa-headset"></i>', '<i class="fa-solid fa-paperclip"></i>', '<i class="fa-solid fa-briefcase"></i>', '<i class="fa-solid fa-calculator"></i>' ];
let flippedCards = []; let matchedPairs = 0; let memoryLocked = false;
window.initMemoryGame = function() { const board = document.getElementById('memory-board'); const statusText = document.getElementById('memory-status'); board.innerHTML = ''; flippedCards = []; matchedPairs = 0; memoryLocked = false; statusText.innerText = "Temukan semua pasangan!"; statusText.className = "text-sm font-bold text-slate-600 dark:text-slate-300 mb-4 bg-gray-100 dark:bg-slate-700 py-2 rounded-xl"; let memoryCards = [...memoryIcons, ...memoryIcons]; memoryCards.sort(() => Math.random() - 0.5); memoryCards.forEach((icon, index) => { const card = document.createElement('button'); card.className = "h-16 bg-gray-100 dark:bg-slate-700 rounded-xl text-2xl flex items-center justify-center transition-all shadow-inner text-transparent border border-gray-200 dark:border-slate-600 hover:bg-gray-200 dark:hover:bg-slate-600 active:scale-95"; card.dataset.index = index; card.dataset.icon = icon; card.innerHTML = icon; card.onclick = () => flipMemoryCard(card); board.appendChild(card); }); };
window.flipMemoryCard = function(card) { if (memoryLocked || card.classList.contains('matched') || flippedCards.includes(card)) return; card.classList.remove('text-transparent', 'bg-gray-100', 'dark:bg-slate-700'); card.classList.add('bg-purple-100', 'text-purple-600', 'dark:bg-purple-900/40', 'dark:text-purple-300'); flippedCards.push(card); if (flippedCards.length === 2) { memoryLocked = true; setTimeout(checkMemoryMatch, 700); } };
window.checkMemoryMatch = function() { const [card1, card2] = flippedCards; if (card1.dataset.icon === card2.dataset.icon) { card1.classList.add('matched', 'bg-green-100', 'text-green-600', 'dark:bg-green-900/40', 'dark:text-green-400'); card1.classList.remove('bg-purple-100', 'text-purple-600', 'dark:bg-purple-900/40', 'dark:text-purple-300'); card2.classList.add('matched', 'bg-green-100', 'text-green-600', 'dark:bg-green-900/40', 'dark:text-green-400'); card2.classList.remove('bg-purple-100', 'text-purple-600', 'dark:bg-purple-900/40', 'dark:text-purple-300'); matchedPairs++; if (matchedPairs === memoryIcons.length) { const statusText = document.getElementById('memory-status'); statusText.innerText = "Yeay! Kamu ingat semuanya! 🎉"; statusText.className = "text-sm font-bold text-green-800 dark:text-green-300 mb-4 bg-green-100 dark:bg-green-900/50 py-2 rounded-xl transition-all"; } } else { card1.classList.add('text-transparent', 'bg-gray-100', 'dark:bg-slate-700'); card1.classList.remove('bg-purple-100', 'text-purple-600', 'dark:bg-purple-900/40', 'dark:text-purple-300'); card2.classList.add('text-transparent', 'bg-gray-100', 'dark:bg-slate-700'); card2.classList.remove('bg-purple-100', 'text-purple-600', 'dark:bg-purple-900/40', 'dark:text-purple-300'); } flippedCards = []; memoryLocked = false; };